"""
train_unet.py
==============
U-Net baseline for binary coronary vessel segmentation on ARCADE syntax.

Run after convert_mask.py has produced binary masks.

Usage:
    python train_unet.py
    python train_unet.py --epochs 50 --batch-size 8

Output:
    checkpoints/unet_best.pth
    results/unet_metrics.json
    results/unet_predictions/
"""

import argparse
import json
import time
from pathlib import Path

import cv2
import numpy as np
import segmentation_models_pytorch as smp
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

from augmentations import get_transforms


# ──────────────────────────────────────────────────────────────
# Config
# ──────────────────────────────────────────────────────────────

def get_cfg(args: argparse.Namespace) -> dict:
    return {
        "data_root":      args.data_root,
        "encoder":        "resnet34",
        "encoder_weights":"imagenet",
        "image_size":     512,
        "batch_size":     args.batch_size,
        "num_workers":    4,
        "epochs":         args.epochs,
        "lr":             1e-4,
        "weight_decay":   1e-4,
        "checkpoint_dir": "checkpoints",
        "results_dir":    "results",
        "seed":           42,
    }


# ──────────────────────────────────────────────────────────────
# Dataset
# ──────────────────────────────────────────────────────────────

class ArcadeDataset(Dataset):
    """
    Loads (XCA image, binary vessel mask) pairs from ARCADE syntax dataset.

    Images  : data/syntax/{split}/images/*.png  — grayscale XCA frames
    Masks   : data/masks/{split}/*.png          — binary 0/255 generated by convert_masks.py
    """

    def __init__(self, split: str, data_root: str, transform=None):
        self.transform = transform
        root = Path(data_root)

        img_dir  = root / "syntax" / split / "images"
        mask_dir = root / "masks"  / split

        if not img_dir.exists():
            raise FileNotFoundError(
                f"Image directory not found: {img_dir}\n"
                "Check --data-root and that ARCADE dataset is in place."
            )
        if not mask_dir.exists():
            raise FileNotFoundError(
                f"Mask directory not found: {mask_dir}\n"
                "Run convert_masks.py first."
            )

        # Pair images with their masks (only keep pairs where both exist)
        self.pairs = []
        for img_path in sorted(img_dir.glob("*.png")):
            mask_path = mask_dir / img_path.name
            if mask_path.exists():
                self.pairs.append((img_path, mask_path))
            else:
                print(f"[WARN] No mask for {img_path.name} — skipping")

        if not self.pairs:
            raise RuntimeError(f"No valid image-mask pairs found for split='{split}'")

        print(f"  [{split}] {len(self.pairs)} image-mask pairs loaded")

    def __len__(self) -> int:
        return len(self.pairs)

    def __getitem__(self, idx: int) -> dict:
        img_path, mask_path = self.pairs[idx]

        # Load image — grayscale XCA, convert to 3-channel RGB for ImageNet encoder
        img = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)
        if img is None:
            raise FileNotFoundError(f"Cannot read image: {img_path}")
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)

        # Load mask — binary 0/255, convert to float 0.0/1.0
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if mask is None:
            raise FileNotFoundError(f"Cannot read mask: {mask_path}")
        mask = (mask > 127).astype(np.float32)

        if self.transform:
            aug  = self.transform(image=img, mask=mask)
            img  = aug["image"]               # torch.Tensor (3, H, W)
            mask = aug["mask"].unsqueeze(0)   # torch.Tensor (1, H, W)

        return {"image": img, "mask": mask, "stem": img_path.stem}


# ──────────────────────────────────────────────────────────────
# Loss
# ──────────────────────────────────────────────────────────────

class BCEDiceLoss(nn.Module):
    """
    BCE + Dice loss combined (equal weights).

    Dice loss is critical for vessel segmentation because vessels occupy
    only ~5–15% of the image — BCE alone would ignore them.

    Reference: Milletari et al., V-Net, 3DV 2016.
    """

    def __init__(self, smooth: float = 1.0):
        super().__init__()
        self.smooth = smooth
        self.bce    = nn.BCEWithLogitsLoss()

    def forward(self, logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
        bce_loss = self.bce(logits, targets)

        probs  = torch.sigmoid(logits)
        p_flat = probs.view(-1)
        t_flat = targets.view(-1)
        inter  = (p_flat * t_flat).sum()
        dice_loss = 1.0 - (2.0 * inter + self.smooth) / (
            p_flat.sum() + t_flat.sum() + self.smooth
        )

        return 0.5 * bce_loss + 0.5 * dice_loss


# ──────────────────────────────────────────────────────────────
# Metrics
# ──────────────────────────────────────────────────────────────

def compute_metrics(
    preds_bin: torch.Tensor,  # (B,1,H,W) binary {0,1}
    targets:   torch.Tensor,  # (B,1,H,W) binary {0,1}
    smooth:    float = 1e-6,
) -> dict[str, float]:
    p = preds_bin.float().view(-1)
    t = targets.float().view(-1)

    tp = (p * t).sum()
    fp = (p * (1 - t)).sum()
    fn = ((1 - p) * t).sum()
    tn = ((1 - p) * (1 - t)).sum()

    dice     = (2 * tp + smooth) / (2 * tp + fp + fn + smooth)
    iou      = (tp + smooth) / (tp + fp + fn + smooth)
    px_acc   = (tp + tn) / (tp + tn + fp + fn + smooth)
    precision= (tp + smooth) / (tp + fp + smooth)
    recall   = (tp + smooth) / (tp + fn + smooth)

    return {
        "dice":      dice.item(),
        "iou":       iou.item(),
        "px_acc":    px_acc.item(),
        "precision": precision.item(),
        "recall":    recall.item(),
    }


# ──────────────────────────────────────────────────────────────
# Train / eval loops
# ──────────────────────────────────────────────────────────────

def train_epoch(model, loader, optimizer, criterion, device) -> dict:
    model.train()
    total_loss = 0.0
    totals = {k: 0.0 for k in ["dice", "iou", "px_acc", "precision", "recall"]}

    for batch in tqdm(loader, desc="  train", leave=False):
        images  = batch["image"].to(device)
        targets = batch["mask"].to(device)

        optimizer.zero_grad()
        logits = model(images)
        loss   = criterion(logits, targets)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        with torch.no_grad():
            preds_bin = (torch.sigmoid(logits) > 0.5).long()
            for k, v in compute_metrics(preds_bin, targets).items():
                totals[k] += v

    n = len(loader)
    return {"loss": total_loss / n, **{k: v / n for k, v in totals.items()}}


@torch.no_grad()
def eval_epoch(model, loader, criterion, device) -> dict:
    model.eval()
    total_loss = 0.0
    totals = {k: 0.0 for k in ["dice", "iou", "px_acc", "precision", "recall"]}

    for batch in tqdm(loader, desc="  val  ", leave=False):
        images  = batch["image"].to(device)
        targets = batch["mask"].to(device)

        logits = model(images)
        total_loss += criterion(logits, targets).item()

        preds_bin = (torch.sigmoid(logits) > 0.5).long()
        for k, v in compute_metrics(preds_bin, targets).items():
            totals[k] += v

    n = len(loader)
    return {"loss": total_loss / n, **{k: v / n for k, v in totals.items()}}


# ──────────────────────────────────────────────────────────────
# Save sample predictions
# ──────────────────────────────────────────────────────────────

@torch.no_grad()
def save_predictions(model, loader, device, out_dir: Path, n: int = 10) -> None:
    """Save side-by-side panels: XCA | GT | prediction."""
    out_dir.mkdir(parents=True, exist_ok=True)
    model.eval()
    saved = 0

    mean = np.array([0.485, 0.456, 0.406])
    std  = np.array([0.229, 0.224, 0.225])

    for batch in loader:
        if saved >= n:
            break

        images  = batch["image"].to(device)
        targets = batch["mask"]
        stems   = batch["stem"]

        logits    = model(images)
        preds_bin = (torch.sigmoid(logits) > 0.5).cpu().numpy()

        for i in range(len(stems)):
            if saved >= n:
                break

            # Denormalize image for display
            img_np = images[i].cpu().numpy().transpose(1, 2, 0)
            img_np = ((img_np * std + mean) * 255).clip(0, 255).astype(np.uint8)
            img_gray = cv2.cvtColor(img_np, cv2.COLOR_RGB2GRAY)

            gt_mask   = (targets[i, 0].numpy() * 255).astype(np.uint8)
            pred_mask = (preds_bin[i, 0]       * 255).astype(np.uint8)

            # Side-by-side panel: original | GT | prediction
            panel = np.hstack([img_gray, gt_mask, pred_mask])

            # Add metric score to filename for quick quality check
            dice = compute_metrics(
                torch.from_numpy(preds_bin[i:i+1]),
                targets[i:i+1].long(),
            )["dice"]

            fname = f"{stems[i]}_dice{dice:.3f}.png"
            cv2.imwrite(str(out_dir / fname), panel)
            saved += 1

    print(f"  Saved {saved} prediction panels → {out_dir}/")


# ──────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────

def main(args: argparse.Namespace) -> None:
    cfg = get_cfg(args)

    # Reproducibility
    torch.manual_seed(cfg["seed"])
    np.random.seed(cfg["seed"])

    # ── Device ────────────────────────────────────────────────
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\nDevice: {device}")
    if torch.cuda.is_available():
        for i in range(torch.cuda.device_count()):
            name = torch.cuda.get_device_name(i)
            vram = torch.cuda.get_device_properties(i).total_memory / 1e9
            print(f"  GPU {i}: {name}  ({vram:.1f} GB)")

    Path(cfg["checkpoint_dir"]).mkdir(parents=True, exist_ok=True)
    Path(cfg["results_dir"]).mkdir(parents=True, exist_ok=True)

    # ── Data ──────────────────────────────────────────────────
    print("\nLoading datasets...")
    train_ds = ArcadeDataset("train", cfg["data_root"],
                             transform=get_transforms("train"))
    val_ds   = ArcadeDataset("val",   cfg["data_root"],
                             transform=get_transforms("val"))

    train_loader = DataLoader(
        train_ds, batch_size=cfg["batch_size"], shuffle=True,
        num_workers=cfg["num_workers"], pin_memory=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=cfg["batch_size"], shuffle=False,
        num_workers=cfg["num_workers"], pin_memory=True,
    )

    # ── Model ─────────────────────────────────────────────────
    # U-Net + ResNet-34 (ImageNet pretrained)
    model = smp.Unet(
        encoder_name    = cfg["encoder"],
        encoder_weights = cfg["encoder_weights"],
        in_channels     = 3,
        classes         = 1,
        activation      = None,  # raw logits — loss handles sigmoid
    )

    if torch.cuda.device_count() > 1:
        print(f"\nUsing {torch.cuda.device_count()} GPUs")
        model = nn.DataParallel(model)
    model = model.to(device)

    n_params = sum(p.numel() for p in model.parameters()) / 1e6
    print(f"Parameters: {n_params:.1f}M")

    # ── Loss & optimiser ──────────────────────────────────────
    criterion = BCEDiceLoss()
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=cfg["lr"],
        weight_decay=cfg["weight_decay"],
    )
    # Cosine annealing LR schedule
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=cfg["epochs"], eta_min=1e-6,
    )

    # ── Training loop ─────────────────────────────────────────
    best_val_dice = 0.0
    ckpt_path = Path(cfg["checkpoint_dir"]) / "unet_best.pth"
    history   = []

    header = (f"{'Epoch':>6} | {'Loss':>8} | {'Tr.Dice':>8} | "
              f"{'Val.Dice':>9} | {'Val.IoU':>8} | {'LR':>9}")
    print(f"\n{header}")
    print("─" * len(header))

    for epoch in range(1, cfg["epochs"] + 1):
        t0 = time.time()

        tr = train_epoch(model, train_loader, optimizer, criterion, device)
        vl = eval_epoch(model, val_loader,   criterion, device)
        scheduler.step()

        lr  = optimizer.param_groups[0]["lr"]
        sec = time.time() - t0

        print(f"{epoch:>6} | {tr['loss']:>8.4f} | {tr['dice']:>8.4f} | "
              f"{vl['dice']:>9.4f} | {vl['iou']:>8.4f} | {lr:>9.2e}  "
              f"({sec:.0f}s)")

        history.append({"epoch": epoch, "train": tr, "val": vl})

        if vl["dice"] > best_val_dice:
            best_val_dice = vl["dice"]
            state = (model.module.state_dict()
                     if isinstance(model, nn.DataParallel)
                     else model.state_dict())
            torch.save({
                "epoch":      epoch,
                "state_dict": state,
                "val_dice":   best_val_dice,
                "cfg":        cfg,
            }, ckpt_path)
            print(f"         ↑ best val Dice {best_val_dice:.4f} — checkpoint saved")

    # ── Test evaluation ───────────────────────────────────────
    print("\n" + "=" * 55)
    print("Loading best checkpoint for TEST evaluation...")

    ckpt = torch.load(ckpt_path, map_location=device)
    best_model = smp.Unet(
        encoder_name    = cfg["encoder"],
        encoder_weights = None,
        in_channels     = 3,
        classes         = 1,
        activation      = None,
    ).to(device)
    best_model.load_state_dict(ckpt["state_dict"])

    try:
        test_ds = ArcadeDataset("test", cfg["data_root"],
                                transform=get_transforms("val"))
        test_loader = DataLoader(
            test_ds, batch_size=cfg["batch_size"],
            shuffle=False, num_workers=cfg["num_workers"],
        )
        test_m = eval_epoch(best_model, test_loader, criterion, device)

        print("\n┌──────────────────────────────────┐")
        print("│  U-Net Baseline — TEST RESULTS    │")
        print("├──────────────────────────────────┤")
        for k, v in test_m.items():
            if k != "loss":
                print(f"│  {k:<14} {v:.4f}             │")
        print("└──────────────────────────────────┘")

        # Sample prediction panels
        pred_dir = Path(cfg["results_dir"]) / "unet_predictions"
        save_predictions(best_model, test_loader, device, pred_dir, n=12)

        # Metrics JSON
        results = {
            "model":         "U-Net (ResNet-34, ImageNet pretrained)",
            "dataset":       "ARCADE syntax — binary vessel segmentation",
            "split":         "test",
            "best_val_dice": round(best_val_dice, 4),
            "test_metrics":  {k: round(v, 4) for k, v in test_m.items()},
            "config":        cfg,
        }
        out_json = Path(cfg["results_dir"]) / "unet_metrics.json"
        with open(out_json, "w") as f:
            json.dump(results, f, indent=2)
        print(f"\nResults → {out_json}")

    except FileNotFoundError:
        print("[SKIP] Test split not found — run on val split manually.")

    print("\nDone.")


# ──────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="U-Net baseline for ARCADE coronary vessel segmentation"
    )
    parser.add_argument("--data-root",  default="data",
                        help="Root folder containing syntax/ and masks/ subfolders")
    parser.add_argument("--epochs",     type=int, default=50)
    parser.add_argument("--batch-size", type=int, default=8,
                        help="Per-GPU batch size. Total = batch_size × n_GPUs")
    main(parser.parse_args())